apiVersion: v1
kind: ReplicationController
metadata:
  name: datav-web
  labels:
    name: datav-web
spec:
  replicas: 1
  selector:
    name: datav-web
  template:
    metadata:
      labels:
        name: datav-web
    spec:
      containers:
      - name: datav-web
        image: reg.icity-os.com/cityos/datav-web:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
